### ISSUE TITLE
Add configuration to serve aspx files from a specific folder like Pages

### ISSUE THREAD

**Issue by Code-DJ** [CoreWebForms/CoreWebForms#146]
Is it possible to serve the aspx files out of the Pages or another configurable folder?

Is this doable? if you point me in the direction can create a PR.

**Comment by twsouthwick** [comment]
The compilation currently grabs the content directory from IHostEnvironment. For example see:

https://github.com/CoreWebForms/CoreWebForms/blob/69d9da0e56b495607190023a3de18506c0b2837c/src/Compiler.Dynamic/SystemWebCompilation.cs#L82

Feel free to move it to `PageCompilationOptions` and have it default to being set by `IHostEnvironment`. Then you could replace it, create a composite file provider, etc

**Comment by twsouthwick** [comment]
I assigned you if that's ok :)
