### ISSUE TITLE
Control NullReferenceException

### ISSUE THREAD

**Issue by Code-DJ** [CoreWebForms/CoreWebForms#188]
The control throws an exception when it needs HttpContext and the Context is not available.

https://github.com/CoreWebForms/CoreWebForms/blob/2039524e094e0e08aa458d0146b364c008708721/src/WebForms/UI/Control.cs#L371

The Features are Set at the Page level but not at the Control level. Additionally, a Control may not be added to the Page yet and hence we cannot just change it to `Page.GetHierarchicalFeature<HttpContext>()`.

This works but I assume there is a reason for going with `GetHierarchicalFeature<HttpContext>` vs `HttpContext.Current`.

```cs
protected internal virtual HttpContext Context => GetHierarchicalFeature<HttpContext>() ?? HttpContext.Current;
```

**Comment by twsouthwick** [comment]
I actually thought I had removed that code - it was supposed to be part of the bootstrapping of the system.

The reason I put it there was to hopefully have a way to not use HttpContext.Current and instead use DI, but it is needed sometimes before a contorl has been added.
