### ISSUE TITLE
asp:scriptmanager tag not recognized as control

### ISSUE THREAD

**Issue by birojnayak** [CoreWebForms/CoreWebForms#20]
It looks like the prefix parsers missing the System.Web.Extension dll.. debugging to fix it.

**Comment by birojnayak** [comment]
We need to extend PageCompilationOptions to include WebExtension dll..
```C#
    public PageCompilationOptions()
    {
        _assemblies = new();
        KnownTags = new List<TagNamespaceRegisterEntry>();

        AddTypeNamespace<Page>("asp");
        AddTypeNamespace<TextBox>("asp");
        //Add below 2 lines and include the extension as dependency in the Compiler
        AddTypeNamespace<ScriptManager>("asp");
        AddTypeNamespace<ListView>("asp");


        AddAssembly(typeof(HttpUtility).Assembly);
        AddAssembly(typeof(IHttpHandler).Assembly);
        AddAssembly(typeof(HttpContext).Assembly);
    }
```

**Comment by Code-DJ** [comment]
Hi, you need only one of `AddTypeNamespace<ScriptManager>("asp");` or `AddTypeNamespace<ListView>("asp");` since both are in the same project.

**Comment by birojnayak** [comment]
Closing...  part of PR #32 , we have added extension method ```AddWebFormsExtensions``` as mentioned here=>  https://github.com/CoreWebForms/CoreWebForms/blob/main/src/Extensions/Extensions.cs#L12
