### ISSUE TITLE
Porting Microsoft.AspNet.Web.Optimization.WebForms 

### ISSUE THREAD

**Issue by birojnayak** [CoreWebForms/CoreWebForms#22]
Porting Porting Microsoft.AspNet.Web.Optimization.WebForms

**Comment by twsouthwick** [comment]
This has already started. Can you enumerate what scenarios you want to enable? Initially, I don't want to worry about actually optimizing anything - I want it to serve up files registered with it. We can enable an interface that could be implemented to actually do the minimizing/bundling if desired

**Comment by twsouthwick** [comment]
closing this as it's now ported
