### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by gumbarros** [CoreWebForms/CoreWebForms#244]
We used [SimpleInjector](https://docs.simpleinjector.org/en/latest/webformsintegration.html) in our WebForms project thinking an ASP.NET Core port would never come. Will this work in CoreWebForms?

Btw congrats on the project, looking forward to share with my team and use in production when ready.

**Comment by birojnayak** [comment]
+1 on giving us feedback to prioritize items which needed for users

**Comment by gumbarros** [comment]
> Which part are you referring to? I'm making use of the built in di patterns and using `ActivatorUtilities` where possible to enable DI patterns, but it depends on what you're using.

Do a Global.asax exists so I can enable `SimpleInjector`? If not, is there a way to activate services based on [Import] attribute? This would solve my problem.

Also if this is a side project, will ever be a "official" NuGet.org package like `CoreWCF`?

**Comment by twsouthwick** [comment]
> Do a Global.asax exists so I can enable SimpleInjector? If not, is there a way to activate services based on [Import] attribute? This would solve my problem.

That's already possible with the System.Web adapters (which is an official project). However, you may be able to make it work just in ASP.NET Core itself by providing your own DI framework there

> Also if this is a side project, will ever be a "official" NuGet.org package like CoreWCF?

No idea :( if anything, if there is a community supporting it then it can at least be a bridge to ASP.NET Core. My ideal world would be that this makes migrating to newer (more modern) technologies that much easier so it would be a stepping stone to blazor/mvc/etc

**Comment by birojnayak** [comment]
@gumbarros here is an [Global.asax example](https://github.com/CoreWebForms/Samples/blob/main/samples/WingTipToys/src/Program.cs#L31).

Our present priority is add as many projects to [samples](https://github.com/CoreWebForms/Samples/tree/main/samples) and bridge the feature gaps and we will take the decision going to Nuget(which I am also looking forward to) based on community involvement and feature coverage.

**Comment by gumbarros** [comment]
> @gumbarros here is an [Global.asax example](https://github.com/CoreWebForms/Samples/blob/main/samples/WingTipToys/src/Program.cs#L31).
> 
> Our present priority is add as many projects to [samples](https://github.com/CoreWebForms/Samples/tree/main/samples) and bridge the feature gaps and we will take the decision going to Nuget(which I am also looking forward to) based on community involvement and feature coverage.

Probably sharing in C# discord server and .NET Reddit will generate great community involvement.

In my opinion a WebForms port to Core is something really really critical that would benefit the community.

**Comment by trynn** [comment]
Hey Folks!
First i wanted to thank all contributors for the huge effort for make this real.
After finding this project, i tried to convert one of our legacy-webforms projects.

Have it up and running, but to extend to the full code, the Major-Issue i run into now is Injection for pages (*.aspx).
We have setup our project according to Autofac docs. (https://autofac.readthedocs.io/en/latest/integration/webforms.html)

Tagging the class with `[InjectUnsetProperties]` to enable auto-injection into public properties of the page.
Is there any replacement available yet?

Unfortunatly, this is a migration-breaker at the moment for my project. Everything else looks pretty fine.
Most rewrite required was HttpContext code, and making our own code fit for linux. (running in docker)
Hope this feedback helps.

**Comment by gumbarros** [comment]
@trynn  if you find a solution to your problem, please send here, DI is the only stopping me to use the package too.

**Comment by twsouthwick** [comment]
I did the following in a sample:

https://github.com/CoreWebForms/Samples/blob/main/samples/eShop/Program.cs#L47-L57

**Comment by trynn** [comment]
Thanks @twsouthwick 
Just tested your solution and it looks good. Will reply again if i can find any caviats.

**Comment by twsouthwick** [comment]
I'm going to close this issue as any specific DI issues should be opened in their own issue so we can track it more easily. If I missed something here, let me know
