### ISSUE TITLE
List of pending items

### ISSUE THREAD

**Issue by Code-DJ** [CoreWebForms/CoreWebForms#246]
Is it possible to create a list of all pending items? It will make it easier to see what's planned/remaining and may be contribute if possible.

**Comment by twsouthwick** [comment]
That's what the issues are :) I've been approaching it as creating an issue for a theme I'm working on and then picking away at it. If you have feature requests, new issues will be the best way to track it. If an existing issue (or one you create) is one you want to work on, just volunteer on the issue and we'll assign it to you. Happy to help with design decisions - I've developed a pattern that seems to be working.... I'll try to get that written down this week.

**Comment by Code-DJ** [comment]
@birojnayak mentioned "we have so many other higher priority items to port in.." in another issue so I assumed there was a list outside of open issues.
