### ISSUE TITLE
Register TagPrefix with "tagName" and "src"

### ISSUE THREAD

**Issue by erfan-kamali-azihub** [CoreWebForms/CoreWebForms#247]
How to register TagPrefix with tagName and src attributes? What is the equivalent of this in CoreWebForms ?

`<%@ Register tagPrefix="xyz" tagName="Navigation" src="~/Controls/Navigation.ascx" %>`

**Comment by twsouthwick** [comment]
@erfan-kamali-azihub I'm going to close this, but if you find it's not working, please give us details
