### ISSUE TITLE
handling session key

### ISSUE THREAD

**Issue by birojnayak** [CoreWebForms/CoreWebForms#25]
With SystemWebadapters mandating the session key type, it's would be quite inconvenient for web form apps to find all session keys and put as an extension with type information in the startup. Let's brainstorm the solution around the same.

**Comment by twsouthwick** [comment]
ISessionKeySerializer can be implemented to handle dynamic keys/types if needed. Does that work?

**Comment by birojnayak** [comment]
yes.. closing

**Comment by birojnayak** [comment]
working
