### ISSUE TITLE
Missing Web Controls

### ISSUE THREAD

**Issue by punjabier** [CoreWebForms/CoreWebForms#261]
Hi
Thanks for this amazing work. While trying this project to upgrade an old app, I found some missing web controls.

- System.Web.UI.WebControls.Menu
- System.Web.UI.WebControls.MenuItem
- System.Web.UI.WebControls.MenuItemCollection
- System.Web.UI.WebControls.MenuAdapter
- System.Web.UI.WebControls.CompareValidator

**Comment by birojnayak** [comment]
@punjabier are you interested contributing to this repo? As an example you can get file from  [here](https://github.com/microsoft/referencesource/blob/master/System.Web/UI/WebControls/Menu.cs) and copy to this repo. 

Similarly for other missing controls. Ensure you change the header to reflect MIT open source license.
