### ISSUE TITLE
GridView can ported ? your thought ?

### ISSUE THREAD

**Issue by birojnayak** [CoreWebForms/CoreWebForms#3]
do you think gridview would work, if I bring the codebase ? I am experimenting with this control

**Comment by twsouthwick** [comment]
Feel free to give it a try. The pattern I use is:

1. Copy it over
2. Run `sr-extractor` to generate the (empty) resource entries
3. Apply formatting (i.e. dotnet format)
4. Deal with any API not found.
      > I haven't been too exact with how to document this as it's been a work in in progress, but if you have to remove something, I've settled on `#if PORT_{SOMEBLOCKINGFEATURE}` to exclude it for now. In the future, we could grep the code for `#if PORT_` and get a general idea of what the block issues are

**Comment by birojnayak** [comment]
this is ported
