### ISSUE TITLE
dotnet watch, dotnet run crashes if aspx file is changed

### ISSUE THREAD

**Issue by Code-DJ** [CoreWebForms/CoreWebForms#34]
Tried the following on macOS.

Steps to reproduce:
- Enable dynamic compilation
- Run the sample project (samples/SystemWebUISample) using `dotnet watch` or `dotnet run`
- Save dynamic_page.aspx
- `dotnet watch` throws the following errors:
```
dotnet watch ❌ Exited with error code 139
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...
```
- `dotnet run` stops running and returns to prompt.

If I comment the following line in WebFormsCompilationService.cs `dotnet run` refreshes (doesn't crash). You have to refresh the browser to see the changes. `dotnet watch` continues to crash:

```cs
using (_routes.GetWriteLock()) // in UpdateTypesAsync method
```

**Comment by Code-DJ** [comment]
> I've only been running this with `dotnet run` - happy to take any fixes here :)

That line appeared to be the cause but now after a new rebuild it still crashes, so the problem appears to be elsewhere. The dotnet run just just stops, doesn't write out any exception making it hard to track down. Will keep looking.

**Comment by Code-DJ** [comment]
@twsouthwick `alc.Unload();` in `CompiledPage.cs -> RemovePage` method is causing the crash. If I comment it out, dotnet run continues to work without crash.

Found this fix that's going in .NET 8.0 https://github.com/dotnet/runtime/pull/91283. Not sure if what we have is the same bug.

**Comment by twsouthwick** [comment]
oh interesting. so sometimes we were unloading twice? we should probably figure out why for that.

**Comment by Code-DJ** [comment]
The crash only happens on macOS. On Windows we get file is in use by another process exception - the specific page doesn't work because its been unloaded and can't be compiled due to read error, other pages work.

**Comment by twsouthwick** [comment]
Ah - I've only been using Windows. The dynamic compilation stuff was built up as part of a hackathon, so it followed the goal of *works on my box*. We may need to think more about how to support it

**Comment by twsouthwick** [comment]
@Code-DJ I've reworked that entire area. If you're still interested, can you try with the v0.1.0 release?

**Comment by Code-DJ** [comment]
@twsouthwick cool! it works. Thank you! Is there a way to control the source of aspx files? I like the idea of Pages folder. When I had created the PR, I had used the following which is now old code:

`options.Files = new PhysicalFileProvider(Path.Combine(builder.Environment.ContentRootPath, "Pages"));`
