### ISSUE TITLE
Enable SR.CS (formatted message) in Handler project.

### ISSUE THREAD

**Issue by birojnayak** [CoreWebForms/CoreWebForms#61]
Enable SR.CS (formatted message) in Handler project. Presently this is available in the Webform project, we should enable it in the Handler project to avoid hard coding of messages.

**Comment by twsouthwick** [comment]
Is this is still needed? If we don't want to hard code it, I'd prefer using resx files for resources.

**Comment by birojnayak** [comment]
closing this
