### ISSUE TITLE
Ensuring ASP.NET Ajax control works

### ISSUE THREAD

**Issue by birojnayak** [CoreWebForms/CoreWebForms#9]
This issue tracks efforts and issues related to ASP.NET ajax controls. Whether they work or not ? If not what changes need to be made.

**Comment by birojnayak** [comment]
we need to port ASP.NET ajax controls from Web.Extension..

**Comment by AndersMad** [comment]
Basic AJAX / Partial Update test page.

```
<%@ Page Async="true" Language="C#" AutoEventWireup="true"  %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
	<title>Ajax Test</title>
	<style>
		* { font-family: Consolas; }
		body { background-color: #222; color: #eee;  }
	</style>
</head>
<body>
<form id="form1" runat="server">

	<script runat="server">
		protected void Button1_Click(object sender, EventArgs e) {
			Label1.Text = "I am postyback!";
		}
	</script>

	<p>Should stay GET after click: <b><% Response.Write(Page.Request.HttpMethod); %> </b></p>

	<asp:ScriptManager EnablePartialRendering="true" ID="ScriptManager1" runat="server"></asp:ScriptManager>
	
	<asp:UpdatePanel ID="UpdatePanel1" runat="server">
		<ContentTemplate>
			<asp:Label ID="Label1" runat="server" Text="Do ->"></asp:Label>
			<asp:Button ID="Button1" runat="server" Text="Click" OnClick="Button1_Click" />
		</ContentTemplate>
	</asp:UpdatePanel>
	
</form>
</body>
</html>
```

**Comment by twsouthwick** [comment]
I'm going to go ahead and assign this to me to look into next. I'll keep a running list of items that I find we need to enable to support this.

- [ ] Let's get the reference code in for the types required for the above sample
- [ ] Update ScriptManager to use them
- [ ] ....

**Comment by twsouthwick** [comment]
Update on progress:

Once #136 is merged, the sample @AndersMad gave works. I'm sure things will break for more complex scenarios, but the basic ScriptManager/ajax support will be available to try out more scenarios:

![ajax_example](https://github.com/CoreWebForms/CoreWebForms/assets/583206/77b1d7d6-2f71-4457-ac33-c311c25eb886)

**Comment by twsouthwick** [comment]
Closing as major work is done. Any issues found can be tracked separately
